version: "3.9"
services:
  webapp:
    build: .
    container_name: TestIIS
    ports:
      - "5000:80"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
    restart: unless-stopped
