name: Mirror to GitLab

on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # clone full historyaa

      - name: Push to GitLab
        run: |
          git remote add gitlab "${{ secrets.GL_REPO }}"
          git push gitlab --all
          git push gitlab --tags
