name: Mirror to GitLab

on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # clone full history

      - name: Push to GitLab
        run: |
          git remote add gitlab "${{ secrets.GL_REPO }}"
           BRANCH=${GITHUB_REF#refs/heads/}

           # Cấu hình user cho git
           git config user.email "actions@github.com"
           git config user.name "GitHub Actions Bot"

           # Lấy nhánh gitlab về, nếu không có thì bỏ qua lỗi
           git fetch gitlab $BRANCH || true

           # Rebase nếu có commit mới trên remote
           git rebase gitlab/$BRANCH || true

           # Push branch lên gitlab, có thể cần --force-with-lease nếu non-fast-forward
           git push gitlab $BRANCH --force-with-lease
