name: Mirror to GitLab

on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # clone full history

      - name: Push to GitLab
        run: |
          # Thêm remote gitlab
           git remote add gitlab "${{ secrets.GL_REPO }}"
           
           # Lấy tên nhánh hiện tại từ github.ref, ví dụ refs/heads/main => main
           BRANCH=${GITHUB_REF#refs/heads/}

           # Đồng bộ local với remote gitlab branch (pull rồi rebase)
           git fetch gitlab $BRANCH || true
           git rebase gitlab/$BRANCH || true
           
           # Push branch hiện tại lên gitlab
           git push gitlab $BRANCH
