name: Mirror to GitLab

on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # clone full history

      - name: Push to GitLab
        run: |
          git remote add gitlab "${{ secrets.GL_REPO }}"
          # Mirror push (push tất cả refs, bao gồm branch, tag)
          git push --mirror gitlab
